### ISSUE TITLE
question, not an issue

### ISSUE THREAD

**Issue by webr3** [jcevanco/rcp_bmw_service_0x22#1]
I currently have tertiary knowledge of what's involved in accessing sensor data on f/g series bmw's, however I am somewhat versed in programming and data transformation, so have a very basic and potentially stupid question:

If bimmerlink can access sensor data via an enet cable or device such as an mhd adapter, why do racecapture and others need to tap in to PT-CAN Bus network, rather than reading it in the same manner as bimmerlink does?

**Comment by jcevanco** [comment]
This Service 0x22 script is used via the RCP CAN Port 1 and the Vehicle OBD port to retrieve data in the same manner as using BimmerLink or any other OBD compatible scan tool. As you may know OBD is a synchronous poll-response protocol can only retrieve on item at a time. On the G series, the ZGM latency is around 10ms for standard (0x01) PIDs and around 15ms for module specific (0x22) PIDs. As you increase the number of PIDs you are monitoring, it increases the individual PID update rate (ie. 10 PIDs at 10ms latency means at best your individual PID update rate will be 100ms). An OBD only implementation is quite suitable for many users who only want to log a few items.

The need for taping into the PT-CAN arises with the desire to collect a larger volume of data and with the desire to collect data that is not available vid standard OBD queries.

By also taping into the PT-CAN via CAN Port 2 on the RCP device, it allows the device to passively collect data from the high-speed communication between modules on the CAN Bus. It’s essentially running as a traffic sniffer and uses the configured message ID mappings to update the log data every time the target message appears on the bus.

Ideally, you’d configure the RCP device to collect as much as possible from the PT-CAN and only configure OBD PIDs for the items not available on the PT-CAN. This dual approach provides for the most efficient manner to collect the desired data.

**Comment by webr3** [comment]
Thanks, getting in to a bit of a rabbit hole here, was looking in to getting my first track car (b58 based) and wanted to data log to both identify issues/learn and get feedback on timing, but as I've dug through products I'm not impressed with what's available regardless of budget - have you had experience with, 

-- https://www.csselectronics.com/pages/can-bus-hardware-products
-- https://www.csselectronics.com/pages/can-bus-sniffer-reverse-engineering
-- https://www.savvycan.com/

the contactless adapters look just the ticket but I'm still ramping up on learning here - I have a g series b57 out front i can start hacking with and mapping the can data to ramp up and get to speed

**Comment by jcevanco** [comment]
I just use the RCP. When I want to do CAN/OBD reverse engineering, I just load it with a high-speed logging script and use the serial CLI to pipe the log output to a text file. From there, I run some post processing scripts to break the traffic into manageable groups. It's how I reverse engineered the secondary addressing used by BMW for OBD service 0x22 queries and responses.

**Comment by jcevanco** [comment]
.
